project:
  type: book
  output-dir: docs
  
execute: 
  warning: FALSE
  message: FALSE
  cache: true

comments:
  hypothesis: 
    theme: clean

book:
  title: "Young Of Year Study"
  author: "Michael Hayden"
  date: today
  chapters:
    - index.qmd
    - variationInEmergenceTiming.qmd
    - OtolithRadiusForkLengthRelationship.qmd
    - SizeDisExplanation.qmd 

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    code-fold: true
    code-tools: true
    code-overflow: wrap
    number-depth: 4
    
    include-in-header:
      - file: github-corner.html
    code-link: true
      
  pdf:
    documentclass: scrreprt

editor: source